# Generated by Django 3.1.3 on 2020-11-25 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_auto_20201125_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gametype',
            new_name='game_type',
        ),
    ]
