# Generated by Django 3.1.3 on 2020-12-02 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_auto_20201125_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_type',
            new_name='gametype',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', related_query_name='evemt', to='levelupapi.gamer'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='bio',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='GamerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelupapi.event')),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelupapi.gamer')),
            ],
        ),
    ]
